name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build paper
        uses: swissmanu/latex-action@master
        with:
          root_file: paper.tex
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape # allows minted to do its work
      - uses: actions/upload-artifact@master
        with:
          name: PDF
          path: paper.pdf
